os: linux
dist: bionic
language: php

cache:
    directories:
        - $HOME/.composer/cache/files

jobs:
    fast_finish: true
    include:
        - php: 7.4

install:
    - composer update --prefer-dist --no-interaction

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/php-cs-fixer fix --dry-run
    - ./vendor/bin/phpstan analyse
    - ./vendor/bin/phpunit --coverage-clover=build/clover.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
